kind: pipeline
name: default
steps:
  - name: test
    image: golang:1.12
    commands:
      - make test
  - name: build
    image: golang:1.12
    commands:
      - make build
  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - LICENSE
        - Readme.md
        - nft_exporter.*
      when:
        event: tag